<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common.props"/>

  <PropertyGroup>
    <AssemblyName>PoYArchipelago</AssemblyName>
    <Description>An Archipelago mod for Peaks of Yore</Description>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IntermediateOutputPath>../obj/plugin/$(Configuration)/</IntermediateOutputPath>
    <OutputPath>../bin/plugin/$(Configuration.ToLower())/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.36" PrivateAssets="all"/>
  </ItemGroup>

  <Import Condition="Exists('../GamePath.props')" Project="../GamePath.props"/>

  <PropertyGroup Condition="'$(GamePath)' == ''">
    <GamePath Condition="'$(OS)' == 'Unix'">$(HOME)/.local/share/Steam/steamapps/common/Peaks of Yore</GamePath>
    <GamePath Condition="'$(OS)' == 'Windows_NT'">C:/Program Files (x86)/Steam/steamapps/common/Peaks of Yore</GamePath>
  </PropertyGroup>

  <PropertyGroup>
    <GameLibPath>$(GamePath)/Peaks of Yore_Data/Managed</GameLibPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp.dll">
      <HintPath>$(GameLibPath)/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass.dll">
      <HintPath>$(GameLibPath)/Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target
    Name="GeneratePluginVersion"
    BeforeTargets="BeforeCompile">
    <WriteLinesToFile
      File="$(IntermediateOutputPath)/PluginInfo.cs"
      Lines="public static class PluginInfo { public const string PLUGIN_VERSION=&quot;$(Version)&quot;%3B }"
      Overwrite="true"/>
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)/PluginInfo.cs"/>
    </ItemGroup>
  </Target>
</Project>
<!-- vim: set et sw=2 ts=2 ft=xml: -->
